<?php 
global $G_CLASS_FILES;
$G_CLASS_FILES = array(
'BaseController'=>'hicore/BaseController.php',
'BaseModel'=>'hicore/BaseModel.php',
'BaseVisitor'=>'hicore/BaseVisitor.php',
'HiApp'=>'hicore/HiApp.php',
'HiConsoleApp'=>'hicore/HiConsoleApp.php',    
'HiException'=>'hicore/HiException.php',
'HiLog'=>'hicore/HiLog.php',
'Permission'=>'hicore/Permission.php',
'HiDebug'=>'hicore/HiDebug.php',
'AppSettingProvider'=>'hicore/AppSettingProvider.php',
'QueryBuilder'=>'hicore/QueryBuilder.php',
'QueryBuilderServer'=>'hicore/QueryBuilderServer.php',
'QueryBuilderClient'=>'hicore/QueryBuilderClient.php',
'ValidationRule'=>'hicore/ValidationRule.php',
'Validator'=>'hicore/Validator.php',
'HiImage'=>'hicore/HiImage.php',

'HiCache_Exception'=>'hicore/cache/exception/exception.php',
'HiCache_File'=>'hicore/cache/file.php',
'HiCache_Memcached'=>'hicore/cache/memcached.php',
'HiCache_Memcachedb'=>'hicore/cache/memcachedb.php',
'HiCache_XCache'=>'hicore/cache/xcache.php',

'HiDebug_FirePHP'=>'hicore/debug/debug_firephp.php',
'FirePHP'=>'hicore/debug/FirePHP.class.php',

'Hi_ClassNotDefinedException'=>'hicore/exception/classnotdefined_exception.php',
'Hi_filenotfoundexception'=>'hicore/exception/filenotfound_exception.php',
'Hi_illegalfilenameexception'=>'hicore/exception/illegalfilename_exception.php',
'HiLog_Exception'=>'hicore/exception/log_exception.php',

'file'=>'hilib/file.class.php',
'Hidb'=>'hilib/hidb.class.php',
'HiPDO'=>'hilib/hipdo.class.php',
'HiLogicDB' => 'hicore/HiLogicDB.php',
'ShardDAO' => 'hicore/ShardDAO.php',
'CacheDAO' => 'hicore/CacheDAO.php',
'seccode'=>'hilib/seccode.class.php',
'Helper_ImgCode'=>'hilib/seccode.class.php',
'string'=>'hilib/string.class.php',
'HiTemplate'=>'hilib/template.class.php',
'util'=>'hilib/util.class.php',
'Chinese'=>'hilib/chinese.class.php',
'GifMerge'=>'hilib/gifmerge.class.php',
'HiStore'=>'hilib/HiStore.php',
'TqUtil'=>'hilib/TqUtil.class.php', //Some Utils for t.mybaby.com
'PHPMailer'=>'hilib/class.phpmailer.php',
'SinaClient'=>'tools/SinaClient.php',
'QQClient'=>'tools/QQClient.php',
'SinababyClient'=>'tools/SinababyClient.php',
'charts'=>'hilib/charts.class.php',
);
